### ISSUE TITLE
Error: (0,_vueNativeRouter.StackNavigator) is not a function.

### ISSUE THREAD

**Issue by Syltis** [GeekyAnts/vue-native-router#15]
Hi!

I'm using Vue Native and vue-native-router. Following the setup steps I am using StackNavigator, but I get this error. The basic code:

```
import { StackNavigator } from 'vue-native-router';
import Index from "../../index";
import HelloWorld from "../HelloWorld"

const AppNavigation = StackNavigator(
    {
        Home: Index,
        HelloWorld: HelloWorld
    },
    {
        initialRouteName: 'Home',
    }
);

export default {
    components: { AppNavigation }
} 
```

My dependencies:
```
"dependencies": {
    "expo": "^34.0.1",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-paper": "^2.16.0",
    "react-native-reanimated": "^1.1.0",
    "react-native-web": "^0.11.4",
    "vue-material": "^1.0.0-beta-11",
    "vue-native-core": "0.1.0",
    "vue-native-helper": "0.1.0",
    "vue-native-router": "^0.1.0",
    "vuelidate": "^0.7.4"
  },
  "devDependencies": {
    "@babel/core": "7.5.5",
    "babel-preset-expo": "^6.0.0",
    "vue-native-scripts": "0.0.16"
  },
  "private": true
```

**Comment by Syltis** [comment]
Closed by mistake.

**Comment by hyvikk** [comment]
having same issue here.

**Comment by CraigA-ZA** [comment]
This issue seems to be because react-navigation v3 completely changed the library. The StackNavigator function is now called createStackNavigator... but it also works a bit differently. I have not yet found the correct way to implement it.
https://stackoverflow.com/questions/53367195/invariant-violation-the-navigation-prop-is-missing-for-this-navigator

**Comment by RishabhKarnad** [comment]
@Syltis As was mentioned by @CraigA-ZA, this is because `react-navigation` v3 replaced `StackNavigator` with `createStackNavigator`. You will also need to wrap the top level navigator with `createAppContainer`

The breaking changes and steps to upgrade are listed in the release notes here:
https://github.com/GeekyAnts/vue-native-router/releases/tag/v0.1.0

Apologies that the documentation hasn't yet been updated. It will be done soon.
