### ISSUE TITLE
Unable to edit or modify appbar properties

### ISSUE THREAD

**Issue by Flamz23** [GeekyAnts/vue-native-router#40]
I've been trying to edit/modify the app bar properties (e.g change it's color, add text or icons) but it seems that it isn't possible anymore.

Part of the reason is that in the example app the doc provides (e.g [KitchenSink](https://github.com/GeekyAnts/KitchenSink-Vue-Native)), they seem to be using a different component naming scheme as shown [here](https://github.com/GeekyAnts/KitchenSink-Vue-Native/blob/master/src/screens/header/header1.vue) which is completely different from what's in the docs

How exactly is its default styling supposed to be changed.

While I have your attention could the docs also be updated to reflect what exactly `Header1: { screen: Header1Screen },` means and its usage in [app.vue](https://github.com/GeekyAnts/KitchenSink-Vue-Native/blob/master/src/App.vue) in the kitchenSink app code

**Comment by RishabhKarnad** [comment]
The KitchenSink app uses NativeBase components, such as the Header component. The styling is done using NativeBase's API:
https://docs.nativebase.io/docs/ThemeVariables.html

The `Header1: { screen: Header1Screen }` simply refers to a demo screen showcasing a custom header component.

To customise the header styling in vue-native-router, you can use the config supported by react-navigation 4:
https://reactnavigation.org/docs/4.x/headers#sharing-common-navigationoptions-across-screens

Since `static` properties are not supported in vue SFC components, you will need to work with `defaultNavigationOptions`
