### ISSUE TITLE
Dark theme in vue native

### ISSUE THREAD

**Issue by Corymillz** [GeekyAnts/vue-native-router#44]
I have been trying to implement dark theme in vue native but no luck yet. According to documentation on react navigation theme. I added ````theme="dark"```` to the app navigator

````
<app-navigator theme="dark"  ></app-navigator>
````
but nothing seem to happen. I have also tried a bunch of other things from the documentation. Please how does it work in vue native?

**Comment by RishabhKarnad** [comment]
You may have added the theme name in the top level navigator, but you will need to consume the theme in the components.

For details in the case of React Navigation 4 / vue-native-router, you can refer to this section in the documentation:
https://reactnavigation.org/docs/4.x/themes/#using-the-currently-selected-theme

Since hooks are not available in vue-native, you would need to use context consumers or context types inside the Vue components.

It is also possible to use provide/inject from Vue to implement global theming. There is no need to rely on the navigation for this. The themed components would still need to make use of inject wherever theme based styling is required.
